name: git-scm
adopt-info: git
license: GPL-2.0-only
summary: Git SCM
description: |
  Git is a fast, scalable, distributed revision control system with an unusually rich command set that provides both high-level operations and full access to internals.
  
  Git is an Open Source project covered by the GNU General Public License version 2 (some parts of it are under different licenses, compatible with the GPLv2). It was originally written by Linus Torvalds with help of a group of hackers around the net.
  
  More on usage at: https://git-scm.com/docs
  
  In order to enable this Snap as your preferred git tool, run: `sudo snap alias git-scm git`
confinement: strict
base: core24
compression: lzo

platforms:
  arm64:
    build-on: [arm64]
  amd64:
    build-on: [amd64]
  armhf:
    build-on: [armhf]

apps:
  git-scm:
    environment:
      MAN_TEST_DISABLE_SYSTEM_CONFIG: 1
      MANPATH: $SNAP/usr/share/man
      GROFF_FONT_PATH: $SNAP/usr/share/groff/current/font
      GROFF_TMAC_PATH: $SNAP/usr/share/groff/current/tmac
      GIT_SSH_COMMAND: ssh -o UserKnownHostsFile=$SNAP_USER_COMMON/known_hosts
    command-chain: [ usr/bin/envsetup ]
    command: usr/bin/git
    plugs: [ home, dot-local-src, removable-media, network, ssh-keys, ssh-public-keys, gpg-keys, gpg-public-keys ]
    completer: usr/share/bash-completion/completions/git

lint:
  ignore:
    - classic
    - library
plugs:
  dot-local-src:
    interface: personal-files
    read: [$HOME/.local/src]
    write: [$HOME/.local/src]
layout:
  /etc/gitconfig:
    bind-file: $SNAP_DATA/etc/gitconfig
  /usr/libexec/git-core:
    symlink: $SNAP/usr/libexec/git-core
  /usr/share/git-core/templates:
    symlink: $SNAP/usr/share/git-core/templates
  /etc/manpath.config:
    bind-file: $SNAP/etc/manpath.config
  /etc/nanorc:
    bind-file: $SNAP/etc/nanorc
  /etc/vim/vimrc:
    bind-file: $SNAP/etc/vim/vimrc
  /usr/share/locale:
    bind: $SNAP/usr/share/locale
  /usr/lib/man-db:
    bind: $SNAP/usr/lib/man-db
  /usr/share/nano:
    bind: $SNAP/usr/share/nano

parts:
  git:
    source: https://github.com/git/git.git
    source-tag: v2.47.0
    source-depth: 1
    plugin: autotools
    autotools-configure-parameters:
      - --prefix=/usr
      - --with-curl
      - --with-expat
    override-build: |
      cd $CRAFT_PART_SRC
      craftctl set version="$(git describe --abbrev=0 --tags)"
      craftctl default
    override-prime: |
      craftctl default
      cd $CRAFT_PART_BUILD
      mkdir -p $CRAFT_PRIME/usr/share/bash-completion/completions/
      cp -a $CRAFT_PART_BUILD/contrib/completion/git-completion.bash $CRAFT_PRIME/usr/share/bash-completion/completions/git
      echo "" >> $CRAFT_PRIME/usr/share/bash-completion/completions/git
      echo "___git_complete git-scm __git_main" >> $CRAFT_PRIME/usr/share/bash-completion/completions/git
      DESTDIR=$CRAFT_PRIME make install-man
    build-packages:
      - build-essential
      - gettext
      - libssl-dev
      - libexpat1-dev
      - zlib1g-dev
      - asciidoc
      - xmlto
    stage-packages:
      - gettext
      - libcurl4-openssl-dev
      - zlib1g
      - openssh-client
      - man
      - man-db
      - groff-base
      - vim
      - nano
      - gpg
  wrappers:
    plugin: dump
    source: snap/local
    organize:
      '*': usr/bin/
